language: node_js
node_js:
- '0.10'
env:
  global:
    secure: KM23I77lhAokpjoaaesgD5OdWMR+IbjI0rK3oSDqYxXeIxhggIFdw/0ya3tBnXRCx9H4QR0bBqE61xTP0ygnTsXmCxU6/MuJEHdjJDRxFl8G4GB9sVRfAl3bXn5EtG0L7yp95Jcdn5jRcRlqtC8cacEbFCFsYElMBqvYv89og+0=
cache:
  directories:
  - node_modules
