language: node_js
node_js:
- '0.10'
env:
  global:
    secure: KM23I77lhAokpjoaaesgD5OdWMR+IbjI0rK3oSDqYxXeIxhggIFdw/0ya3tBnXRCx9H4QR0bBqE61xTP0ygnTsXmCxU6/MuJEHdjJDRxFl8G4GB9sVRfAl3bXn5EtG0L7yp95Jcdn5jRcRlqtC8cacEbFCFsYElMBqvYv89og+0=
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - sudo cp -f build/chrome-sandbox $CHROME_SANDBOX
  - sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX
